import type {
  Tenant,
  User,
  Job,
  Candidate,
  Interview,
  TranscriptSegment,
  InterviewReview,
  GlossaryTerm,
  NLPSettings,
  AdminStats,
} from "./types";

// ─── Tenants ─────────────────────────────────────────────────────────────────

export const TENANTS: Tenant[] = [
  {
    id: "t1",
    name: "PT Mandiri Teknologi",
    shortName: "Mandiri Tech",
    industry: "finance",
    complianceFlag: false,
    logoInitials: "MT",
    color: "#f59e0b",
    planTier: "enterprise",
    interviewHours: 142,
    costThisMonth: 2840000,
    asrProvider: "Google STT",
    wer: 8.2,
    der: 5.1,
    createdAt: "2024-01-15",
  },
  {
    id: "t2",
    name: "StartupID",
    shortName: "StartupID",
    industry: "tech",
    complianceFlag: false,
    logoInitials: "SI",
    color: "#6366f1",
    planTier: "growth",
    interviewHours: 68,
    costThisMonth: 1360000,
    asrProvider: "Whisper",
    wer: 11.4,
    der: 7.8,
    createdAt: "2024-03-08",
  },
  {
    id: "t3",
    name: "Bank Rakyat Nusantara",
    shortName: "BRN",
    industry: "banking",
    complianceFlag: true,
    logoInitials: "BN",
    color: "#10b981",
    planTier: "enterprise",
    interviewHours: 214,
    costThisMonth: 4280000,
    asrProvider: "Azure Speech",
    wer: 6.7,
    der: 4.3,
    createdAt: "2023-11-20",
  },
];

// ─── Users ───────────────────────────────────────────────────────────────────

export const CURRENT_USER: User = {
  id: "u1",
  name: "Sari Dewi Kusuma",
  email: "sari.dewi@mandiritek.co.id",
  role: "Recruiter",
  avatarInitials: "SD",
  tenantId: "t1",
  createdAt: "2024-01-20",
};

export const USERS: User[] = [
  CURRENT_USER,
  {
    id: "u2",
    name: "Budi Hartono",
    email: "budi.h@mandiritek.co.id",
    role: "Interviewer",
    avatarInitials: "BH",
    tenantId: "t1",
    createdAt: "2024-02-01",
  },
  {
    id: "u3",
    name: "Rina Agustina",
    email: "rina@startupid.io",
    role: "Recruiter",
    avatarInitials: "RA",
    tenantId: "t2",
    createdAt: "2024-03-10",
  },
  {
    id: "u4",
    name: "Ahmad Fauzi",
    email: "ahmad.fauzi@brn.co.id",
    role: "Admin",
    avatarInitials: "AF",
    tenantId: "t3",
    createdAt: "2023-11-25",
  },
];

// ─── Jobs ─────────────────────────────────────────────────────────────────────

export const JOBS: Job[] = [
  {
    id: "j1",
    tenantId: "t1",
    title: "Senior Software Engineer — Backend",
    department: "Engineering",
    location: "Jakarta Selatan",
    type: "full-time",
    salaryMin: 25000000,
    salaryMax: 40000000,
    currency: "IDR",
    description:
      "Kami mencari Senior Software Engineer dengan pengalaman dalam membangun sistem distributed scale besar. Kandidat akan bergabung dengan tim inti yang mengerjakan core banking platform generasi berikutnya berbasis microservices.",
    requirements: [
      "Min. 5 tahun pengalaman backend (Go, Java, atau Python)",
      "Familiar dengan Kafka, Redis, PostgreSQL",
      "Pengalaman di industri fintech/banking menjadi nilai tambah",
      "Kemampuan komunikasi dalam Bahasa Indonesia dan Inggris",
    ],
    status: "active",
    applicantCount: 34,
    postedAt: "2026-05-20",
    closesAt: "2026-07-20",
    recruiterName: "Sari Dewi Kusuma",
  },
  {
    id: "j2",
    tenantId: "t1",
    title: "Product Manager — Payments",
    department: "Product",
    location: "Jakarta Pusat (Hybrid)",
    type: "full-time",
    salaryMin: 30000000,
    salaryMax: 50000000,
    currency: "IDR",
    description:
      "Bergabunglah sebagai Product Manager untuk lini produk pembayaran digital kami yang melayani lebih dari 2 juta pengguna aktif bulanan.",
    requirements: [
      "Min. 4 tahun sebagai PM di produk konsumer",
      "Paham ekosistem pembayaran Indonesia (GoPay, OVO, QRIS)",
      "Kemampuan analitis kuat, terbiasa dengan data-driven decisions",
    ],
    status: "active",
    applicantCount: 52,
    postedAt: "2026-05-28",
    closesAt: "2026-07-28",
    recruiterName: "Sari Dewi Kusuma",
  },
  {
    id: "j3",
    tenantId: "t2",
    title: "Full-Stack Engineer",
    department: "Engineering",
    location: "Remote (Indonesia)",
    type: "full-time",
    salaryMin: 15000000,
    salaryMax: 28000000,
    currency: "IDR",
    description:
      "StartupID mencari Full-Stack Engineer yang passionate untuk membangun fitur-fitur baru platform SaaS kami yang sedang tumbuh pesat.",
    requirements: [
      "Proficient in React/Next.js and Node.js",
      "Familiar with TypeScript",
      "Experience with cloud platforms (AWS/GCP)",
    ],
    status: "active",
    applicantCount: 88,
    postedAt: "2026-06-01",
    closesAt: "2026-08-01",
    recruiterName: "Rina Agustina",
  },
  {
    id: "j4",
    tenantId: "t2",
    title: "UI/UX Designer",
    department: "Design",
    location: "Bandung / Remote",
    type: "full-time",
    salaryMin: 12000000,
    salaryMax: 22000000,
    currency: "IDR",
    description:
      "Kami membutuhkan Designer berbakat untuk merancang pengalaman pengguna yang intuitif dan menarik untuk produk kami.",
    requirements: [
      "Portfolio kuat dengan mobile & web design",
      "Mahir menggunakan Figma",
      "Pemahaman dasar frontend (HTML/CSS)",
    ],
    status: "active",
    applicantCount: 41,
    postedAt: "2026-06-05",
    closesAt: "2026-08-05",
    recruiterName: "Rina Agustina",
  },
  {
    id: "j5",
    tenantId: "t3",
    title: "Analis Risiko Kredit Senior",
    department: "Risk Management",
    location: "Jakarta Barat",
    type: "full-time",
    salaryMin: 18000000,
    salaryMax: 32000000,
    currency: "IDR",
    description:
      "BRN mencari Analis Risiko Kredit Senior yang berpengalaman di sektor perbankan untuk memperkuat tim manajemen risiko kami.",
    requirements: [
      "Min. 6 tahun di risk management perbankan",
      "Memahami regulasi OJK dan POJK",
      "Sertifikasi manajemen risiko (FRM/PRM) diutamakan",
    ],
    status: "active",
    applicantCount: 19,
    postedAt: "2026-05-15",
    closesAt: "2026-07-15",
    recruiterName: "Ahmad Fauzi",
  },
  {
    id: "j6",
    tenantId: "t3",
    title: "Compliance Officer — Digital Banking",
    department: "Compliance",
    location: "Jakarta Pusat",
    type: "full-time",
    salaryMin: 22000000,
    salaryMax: 38000000,
    currency: "IDR",
    description:
      "Posisi kritis untuk memastikan seluruh operasional digital banking BRN sesuai dengan ketentuan OJK dan peraturan perundangan yang berlaku.",
    requirements: [
      "Min. 5 tahun di compliance perbankan",
      "Keahlian dalam POJK digital banking",
      "Pengalaman audit internal",
    ],
    status: "active",
    applicantCount: 12,
    postedAt: "2026-06-02",
    closesAt: "2026-08-02",
    recruiterName: "Ahmad Fauzi",
  },
  {
    id: "j7",
    tenantId: "t1",
    title: "Data Scientist — Credit Scoring",
    department: "Data & AI",
    location: "Jakarta Selatan (Hybrid)",
    type: "full-time",
    salaryMin: 20000000,
    salaryMax: 35000000,
    currency: "IDR",
    description:
      "Bergabung dengan tim Data & AI kami untuk mengembangkan model credit scoring next-generation berbasis machine learning.",
    requirements: [
      "Pengalaman ML/DL (Python, scikit-learn, PyTorch)",
      "Familiar dengan data keuangan dan credit risk",
      "Publikasi atau kontribusi open source menjadi nilai plus",
    ],
    status: "paused",
    applicantCount: 27,
    postedAt: "2026-04-10",
    closesAt: "2026-07-10",
    recruiterName: "Sari Dewi Kusuma",
  },
  {
    id: "j8",
    tenantId: "t2",
    title: "DevOps / Platform Engineer",
    department: "Infrastructure",
    location: "Remote (Indonesia)",
    type: "full-time",
    salaryMin: 18000000,
    salaryMax: 30000000,
    currency: "IDR",
    description:
      "We are looking for a DevOps engineer to help us scale our infrastructure as we grow from 50k to 500k users.",
    requirements: [
      "Strong Kubernetes & Docker experience",
      "Terraform / infrastructure-as-code",
      "CI/CD pipelines (GitHub Actions, ArgoCD)",
    ],
    status: "draft",
    applicantCount: 0,
    postedAt: "2026-06-15",
    closesAt: "2026-08-15",
    recruiterName: "Rina Agustina",
  },
];

// ─── Candidates ─────────────────────────────────────────────────────────────

export const CANDIDATES: Candidate[] = [
  {
    id: "c1",
    name: "Arief Rahmat Hidayat",
    email: "arief.rahmat@gmail.com",
    phone: "+62 812-3456-7890",
    location: "Jakarta Selatan",
    currentRole: "Backend Engineer",
    currentCompany: "Tokopedia",
    yearsExperience: 6,
    skills: ["Go", "Kafka", "PostgreSQL", "Kubernetes", "Redis"],
    education: "S1 Ilmu Komputer",
    university: "Universitas Indonesia",
    gpa: 3.72,
    languages: ["Bahasa Indonesia", "English"],
    linkedIn: "linkedin.com/in/arief-rahmat",
    avatarInitials: "AR",
    avatarColor: "#6366f1",
    stage: "interview",
    jobId: "j1",
    jobTitle: "Senior Software Engineer — Backend",
    tenantId: "t1",
    appliedAt: "2026-05-22",
    score: 92,
    tags: ["strong_technical", "culture_fit", "leadership"],
    notes: [
      {
        id: "n1",
        author: "Sari Dewi",
        content: "Kandidat sangat menjanjikan. Pengalaman di Tokopedia relevan. Jadwalkan technical interview segera.",
        createdAt: "2026-05-23",
      },
    ],
    resumeUrl: "/mock/resume-arief.pdf",
  },
  {
    id: "c2",
    name: "Dewi Fitriani Putri",
    email: "dewi.fitriani@outlook.com",
    phone: "+62 821-9876-5432",
    location: "Bandung",
    currentRole: "Software Engineer",
    currentCompany: "Gojek",
    yearsExperience: 4,
    skills: ["Java", "Spring Boot", "MySQL", "Docker", "AWS"],
    education: "S1 Teknik Informatika",
    university: "ITB",
    gpa: 3.85,
    languages: ["Bahasa Indonesia", "English", "Mandarin"],
    linkedIn: "linkedin.com/in/dewi-fitriani",
    avatarInitials: "DF",
    avatarColor: "#f59e0b",
    stage: "screening",
    jobId: "j1",
    jobTitle: "Senior Software Engineer — Backend",
    tenantId: "t1",
    appliedAt: "2026-05-25",
    score: 85,
    tags: ["multilingual", "strong_academics"],
    notes: [],
    resumeUrl: "/mock/resume-dewi.pdf",
  },
  {
    id: "c3",
    name: "Rizky Pratama Nugroho",
    email: "rizky.pratama@email.com",
    phone: "+62 813-5678-9012",
    location: "Jakarta Barat",
    currentRole: "Senior Product Manager",
    currentCompany: "OVO",
    yearsExperience: 7,
    skills: ["Product Strategy", "Data Analysis", "Agile", "SQL", "Figma"],
    education: "S1 Manajemen Bisnis",
    university: "Universitas Gadjah Mada",
    gpa: 3.65,
    languages: ["Bahasa Indonesia", "English"],
    linkedIn: "linkedin.com/in/rizky-pratama",
    avatarInitials: "RP",
    avatarColor: "#10b981",
    stage: "decision",
    jobId: "j2",
    jobTitle: "Product Manager — Payments",
    tenantId: "t1",
    appliedAt: "2026-05-30",
    score: 88,
    tags: ["payments_expert", "leadership"],
    notes: [
      {
        id: "n2",
        author: "Budi Hartono",
        content: "Interview berjalan lancar. Case study payments sangat solid. Perlu validasi referensi.",
        createdAt: "2026-06-08",
      },
    ],
    resumeUrl: "/mock/resume-rizky.pdf",
  },
  {
    id: "c4",
    name: "Siti Nurhaliza Maharani",
    email: "siti.nurhaliza@gmail.com",
    phone: "+62 856-4321-0987",
    location: "Jakarta Pusat",
    currentRole: "Associate Product Manager",
    currentCompany: "GoPay",
    yearsExperience: 3,
    skills: ["Product Management", "User Research", "A/B Testing", "Mixpanel"],
    education: "S1 Teknologi Informasi",
    university: "BINUS University",
    gpa: 3.5,
    languages: ["Bahasa Indonesia", "English"],
    linkedIn: "linkedin.com/in/siti-nurhaliza-m",
    avatarInitials: "SN",
    avatarColor: "#ec4899",
    stage: "screening",
    jobId: "j2",
    jobTitle: "Product Manager — Payments",
    tenantId: "t1",
    appliedAt: "2026-06-01",
    score: 76,
    tags: ["high_potential"],
    notes: [],
    resumeUrl: "/mock/resume-siti.pdf",
  },
  {
    id: "c5",
    name: "Fajar Kurniawan Susanto",
    email: "fajar.ks@gmail.com",
    phone: "+62 878-1234-5678",
    location: "Yogyakarta",
    currentRole: "Full-Stack Developer",
    currentCompany: "Freelance",
    yearsExperience: 3,
    skills: ["React", "Next.js", "Node.js", "TypeScript", "Tailwind"],
    education: "S1 Sistem Informasi",
    university: "UGM",
    gpa: 3.4,
    languages: ["Bahasa Indonesia", "English"],
    linkedIn: "linkedin.com/in/fajar-ks",
    avatarInitials: "FK",
    avatarColor: "#8b5cf6",
    stage: "interview",
    jobId: "j3",
    jobTitle: "Full-Stack Engineer",
    tenantId: "t2",
    appliedAt: "2026-06-03",
    score: 81,
    tags: ["remote_ok", "self_starter"],
    notes: [],
    resumeUrl: "/mock/resume-fajar.pdf",
  },
  {
    id: "c6",
    name: "Indah Permatasari",
    email: "indah.permata@design.co",
    phone: "+62 895-8765-4321",
    location: "Surabaya",
    currentRole: "UX Designer",
    currentCompany: "Bukalapak",
    yearsExperience: 4,
    skills: ["Figma", "User Research", "Prototyping", "Framer", "Sketch"],
    education: "S1 Desain Komunikasi Visual",
    university: "ITS",
    gpa: 3.78,
    languages: ["Bahasa Indonesia", "English", "Japanese (N3)"],
    linkedIn: "linkedin.com/in/indah-permata",
    avatarInitials: "IP",
    avatarColor: "#f43f5e",
    stage: "hired",
    jobId: "j4",
    jobTitle: "UI/UX Designer",
    tenantId: "t2",
    appliedAt: "2026-06-07",
    score: 94,
    tags: ["hired", "top_candidate"],
    notes: [
      {
        id: "n3",
        author: "Rina Agustina",
        content: "Excellent portfolio. Strong communication skills. Hiring recommendation approved.",
        createdAt: "2026-06-14",
      },
    ],
    resumeUrl: "/mock/resume-indah.pdf",
  },
  {
    id: "c7",
    name: "Hendra Wijaya Santoso",
    email: "hendra.ws@email.com",
    phone: "+62 812-9999-8888",
    location: "Jakarta Barat",
    currentRole: "Senior Credit Risk Analyst",
    currentCompany: "Bank Mandiri",
    yearsExperience: 8,
    skills: ["Credit Analysis", "Risk Modeling", "Basel III", "SQL", "R"],
    education: "S2 Manajemen Keuangan",
    university: "Universitas Indonesia",
    gpa: 3.6,
    languages: ["Bahasa Indonesia", "English"],
    linkedIn: "linkedin.com/in/hendra-wijaya",
    avatarInitials: "HW",
    avatarColor: "#0ea5e9",
    stage: "decision",
    jobId: "j5",
    jobTitle: "Analis Risiko Kredit Senior",
    tenantId: "t3",
    appliedAt: "2026-05-17",
    score: 90,
    tags: ["regulatory_expert", "banking_background"],
    notes: [],
    resumeUrl: "/mock/resume-hendra.pdf",
  },
  {
    id: "c8",
    name: "Mega Claudia Setiawan",
    email: "mega.claudia@email.co.id",
    phone: "+62 857-3333-2222",
    location: "Jakarta Timur",
    currentRole: "Risk Manager",
    currentCompany: "CIMB Niaga",
    yearsExperience: 5,
    skills: ["Risk Management", "POJK Compliance", "Credit Scoring", "Excel", "Python"],
    education: "S1 Akuntansi",
    university: "Universitas Trisakti",
    gpa: 3.55,
    languages: ["Bahasa Indonesia", "English", "Mandarin"],
    linkedIn: "linkedin.com/in/mega-claudia",
    avatarInitials: "MC",
    avatarColor: "#f97316",
    stage: "interview",
    jobId: "j5",
    jobTitle: "Analis Risiko Kredit Senior",
    tenantId: "t3",
    appliedAt: "2026-05-20",
    score: 83,
    tags: ["pojk_experienced"],
    notes: [],
    resumeUrl: "/mock/resume-mega.pdf",
  },
  {
    id: "c9",
    name: "Andika Putra Baswara",
    email: "andika.pb@outlook.com",
    phone: "+62 819-7654-3210",
    location: "Jakarta Selatan",
    currentRole: "Compliance Specialist",
    currentCompany: "DBS Indonesia",
    yearsExperience: 6,
    skills: ["Compliance", "POJK", "Internal Audit", "AML/KYC", "Basel"],
    education: "S1 Hukum Bisnis",
    university: "Universitas Padjadjaran",
    gpa: 3.7,
    languages: ["Bahasa Indonesia", "English"],
    linkedIn: "linkedin.com/in/andika-pb",
    avatarInitials: "AB",
    avatarColor: "#14b8a6",
    stage: "hired",
    jobId: "j6",
    jobTitle: "Compliance Officer — Digital Banking",
    tenantId: "t3",
    appliedAt: "2026-06-04",
    score: 91,
    tags: ["hired", "compliance_expert"],
    notes: [],
    resumeUrl: "/mock/resume-andika.pdf",
  },
  {
    id: "c10",
    name: "Yuliana Maharani Putri",
    email: "yuliana.mp@email.com",
    phone: "+62 822-1234-9876",
    location: "Bekasi",
    currentRole: "Data Analyst",
    currentCompany: "Akulaku",
    yearsExperience: 3,
    skills: ["Python", "scikit-learn", "SQL", "Tableau", "Statistics"],
    education: "S1 Statistika",
    university: "IPB University",
    gpa: 3.68,
    languages: ["Bahasa Indonesia", "English"],
    linkedIn: "linkedin.com/in/yuliana-mp",
    avatarInitials: "YP",
    avatarColor: "#a855f7",
    stage: "screening",
    jobId: "j7",
    jobTitle: "Data Scientist — Credit Scoring",
    tenantId: "t1",
    appliedAt: "2026-04-12",
    score: 79,
    tags: ["data_science", "fintech"],
    notes: [],
    resumeUrl: "/mock/resume-yuliana.pdf",
  },
  {
    id: "c11",
    name: "Reza Firmansyah",
    email: "reza.firmansyah@email.com",
    phone: "+62 831-5555-4444",
    location: "Jakarta Utara",
    currentRole: "DevOps Engineer",
    currentCompany: "Traveloka",
    yearsExperience: 5,
    skills: ["Kubernetes", "Terraform", "AWS", "ArgoCD", "Prometheus"],
    education: "S1 Teknik Komputer",
    university: "ITATS",
    gpa: 3.45,
    languages: ["Bahasa Indonesia", "English"],
    linkedIn: "linkedin.com/in/reza-firmansyah",
    avatarInitials: "RF",
    avatarColor: "#84cc16",
    stage: "rejected",
    jobId: "j8",
    jobTitle: "DevOps / Platform Engineer",
    tenantId: "t2",
    appliedAt: "2026-06-10",
    score: 72,
    tags: ["overqualified"],
    notes: [
      {
        id: "n4",
        author: "Rina Agustina",
        content: "Bagus, tapi salary expectation terlalu tinggi untuk stage perusahaan.",
        createdAt: "2026-06-12",
      },
    ],
    resumeUrl: "/mock/resume-reza.pdf",
  },
  {
    id: "c12",
    name: "Kartika Dewi Anggraini",
    email: "kartika.da@gmail.com",
    phone: "+62 815-2222-1111",
    location: "Malang",
    currentRole: "Frontend Developer",
    currentCompany: "Shopee Indonesia",
    yearsExperience: 2,
    skills: ["React", "Vue.js", "TypeScript", "CSS", "Git"],
    education: "S1 Informatika",
    university: "Universitas Brawijaya",
    gpa: 3.8,
    languages: ["Bahasa Indonesia", "English", "Korean (basic)"],
    linkedIn: "linkedin.com/in/kartika-da",
    avatarInitials: "KD",
    avatarColor: "#06b6d4",
    stage: "screening",
    jobId: "j3",
    jobTitle: "Full-Stack Engineer",
    tenantId: "t2",
    appliedAt: "2026-06-08",
    score: 74,
    tags: ["fresh_grad_adjacent", "frontend_strong"],
    notes: [],
    resumeUrl: "/mock/resume-kartika.pdf",
  },
];

// ─── Interviews ──────────────────────────────────────────────────────────────

export const INTERVIEWS: Interview[] = [
  {
    id: "i1",
    candidateId: "c1",
    candidateName: "Arief Rahmat Hidayat",
    jobId: "j1",
    jobTitle: "Senior Software Engineer — Backend",
    tenantId: "t1",
    interviewerName: "Budi Hartono",
    interviewerRole: "Engineering Lead",
    status: "completed",
    scheduledAt: "2026-06-10T10:00:00",
    durationMinutes: 60,
    recordingUrl: "/mock/interview-i1.webm",
    transcriptReady: true,
    language: "mixed",
    asrProvider: "Google STT",
    wer: 7.4,
  },
  {
    id: "i2",
    candidateId: "c3",
    candidateName: "Rizky Pratama Nugroho",
    jobId: "j2",
    jobTitle: "Product Manager — Payments",
    tenantId: "t1",
    interviewerName: "Sari Dewi Kusuma",
    interviewerRole: "Head of Product",
    status: "completed",
    scheduledAt: "2026-06-08T14:00:00",
    durationMinutes: 45,
    recordingUrl: "/mock/interview-i2.webm",
    transcriptReady: true,
    language: "mixed",
    asrProvider: "Google STT",
    wer: 8.1,
  },
  {
    id: "i3",
    candidateId: "c7",
    candidateName: "Hendra Wijaya Santoso",
    jobId: "j5",
    jobTitle: "Analis Risiko Kredit Senior",
    tenantId: "t3",
    interviewerName: "Ahmad Fauzi",
    interviewerRole: "Chief Risk Officer",
    status: "completed",
    scheduledAt: "2026-06-12T09:00:00",
    durationMinutes: 75,
    recordingUrl: "/mock/interview-i3.webm",
    transcriptReady: true,
    language: "id",
    asrProvider: "Azure Speech",
    wer: 6.2,
  },
  {
    id: "i4",
    candidateId: "c5",
    candidateName: "Fajar Kurniawan Susanto",
    jobId: "j3",
    jobTitle: "Full-Stack Engineer",
    tenantId: "t2",
    interviewerName: "Rina Agustina",
    interviewerRole: "CTO",
    status: "live",
    scheduledAt: "2026-06-17T11:00:00",
    durationMinutes: 60,
    transcriptReady: false,
    language: "mixed",
    asrProvider: "Whisper",
  },
  {
    id: "i6",
    candidateId: "c4",
    candidateName: "Dewi Rahayu Pertiwi",
    jobId: "j4",
    jobTitle: "UI/UX Designer",
    tenantId: "t2",
    interviewerName: "Rina Agustina",
    interviewerRole: "CTO",
    status: "live",
    scheduledAt: "2026-06-17T11:30:00",
    durationMinutes: 45,
    transcriptReady: false,
    language: "mixed",
    asrProvider: "Google STT",
  },
  {
    id: "i7",
    candidateId: "c2",
    candidateName: "Siti Nuraini Rahmawati",
    jobId: "j1",
    jobTitle: "Senior Software Engineer — Backend",
    tenantId: "t1",
    interviewerName: "Budi Hartono",
    interviewerRole: "Engineering Lead",
    status: "live",
    scheduledAt: "2026-06-17T11:15:00",
    durationMinutes: 60,
    transcriptReady: false,
    language: "mixed",
    asrProvider: "Google STT",
  },
  {
    id: "i5",
    candidateId: "c8",
    candidateName: "Mega Claudia Setiawan",
    jobId: "j5",
    jobTitle: "Analis Risiko Kredit Senior",
    tenantId: "t3",
    interviewerName: "Ahmad Fauzi",
    interviewerRole: "Chief Risk Officer",
    status: "scheduled",
    scheduledAt: "2026-06-19T10:00:00",
    durationMinutes: 60,
    transcriptReady: false,
    language: "id",
    asrProvider: "Azure Speech",
  },
  {
    id: "i8",
    candidateId: "c6",
    candidateName: "Yusuf Hakim Prasetyo",
    jobId: "j6",
    jobTitle: "Compliance Officer — Digital Banking",
    tenantId: "t3",
    interviewerName: "Ahmad Fauzi",
    interviewerRole: "Chief Risk Officer",
    status: "scheduled",
    scheduledAt: "2026-06-18T14:00:00",
    durationMinutes: 45,
    transcriptReady: false,
    language: "id",
    asrProvider: "Azure Speech",
  },
  {
    id: "i9",
    candidateId: "c9",
    candidateName: "Putri Handayani Santoso",
    jobId: "j2",
    jobTitle: "Product Manager — Payments",
    tenantId: "t1",
    interviewerName: "Sari Dewi Kusuma",
    interviewerRole: "Head of Product",
    status: "scheduled",
    scheduledAt: "2026-06-20T09:30:00",
    durationMinutes: 60,
    transcriptReady: false,
    language: "mixed",
    asrProvider: "Google STT",
  },
];

// ─── Transcript Data ──────────────────────────────────────────────────────────

export const TRANSCRIPT_I1: TranscriptSegment[] = [
  {
    id: "ts1",
    speaker: "S1",
    speakerLabel: "Interviewer",
    startTime: 2,
    endTime: 12,
    text: "Selamat pagi, Arief. Terima kasih sudah hadir hari ini. Bagaimana kondisi Anda?",
    confidence: 0.97,
    isFinal: true,
    hasCodeSwitch: false,
    language: "id",
  },
  {
    id: "ts2",
    speaker: "S2",
    speakerLabel: "Candidate",
    startTime: 14,
    endTime: 28,
    text: "Selamat pagi juga, Pak Budi. Saya baik-baik saja, terima kasih. Saya sangat excited untuk bisa berdiskusi hari ini.",
    confidence: 0.95,
    isFinal: true,
    hasCodeSwitch: true,
    codeSwitchWords: ["excited"],
    language: "mixed",
  },
  {
    id: "ts3",
    speaker: "S1",
    speakerLabel: "Interviewer",
    startTime: 30,
    endTime: 50,
    text: "Baik. Mari kita mulai dengan background Anda. Bisa ceritakan pengalaman Anda di Tokopedia, khususnya dalam membangun distributed systems?",
    confidence: 0.96,
    isFinal: true,
    hasCodeSwitch: true,
    codeSwitchWords: ["distributed systems"],
    keyTerms: ["distributed systems", "Tokopedia"],
    language: "mixed",
  },
  {
    id: "ts4",
    speaker: "S2",
    speakerLabel: "Candidate",
    startTime: 52,
    endTime: 95,
    text: "Tentu. Di Tokopedia, saya bergabung dengan tim platform engineering dan bertanggung jawab untuk membangun service yang menangani order processing dengan throughput sekitar 50 ribu transaksi per detik. Kami menggunakan Go sebagai bahasa utama, dengan Kafka untuk messaging dan PostgreSQL dengan sharding strategy yang custom.",
    confidence: 0.93,
    isFinal: true,
    hasCodeSwitch: true,
    codeSwitchWords: ["platform engineering", "order processing", "throughput", "messaging", "sharding strategy"],
    keyTerms: ["Go", "Kafka", "PostgreSQL", "sharding"],
    language: "mixed",
  },
  {
    id: "ts5",
    speaker: "S1",
    speakerLabel: "Interviewer",
    startTime: 97,
    endTime: 118,
    text: "Menarik sekali. Bagaimana Anda menangani masalah consistency dalam distributed environment seperti itu? Apakah ada trade-off yang harus Anda buat?",
    confidence: 0.94,
    isFinal: true,
    hasCodeSwitch: true,
    codeSwitchWords: ["consistency", "distributed environment", "trade-off"],
    keyTerms: ["consistency", "trade-off"],
    language: "mixed",
  },
  {
    id: "ts6",
    speaker: "S2",
    speakerLabel: "Candidate",
    startTime: 120,
    endTime: 170,
    text: "Iya, ini adalah tantangan utama yang kami hadapi. Kami menerapkan eventual consistency untuk sebagian besar use case, tapi untuk transaksi finansial kami tetap membutuhkan strong consistency. Jadi kami membagi arsitektur menjadi dua layer — hot path yang strong consistent, dan analytics path yang eventual. Ini memang memerlukan kompleksitas tambahan di aplikasi, tapi jauh lebih scalable.",
    confidence: 0.91,
    isFinal: true,
    hasCodeSwitch: true,
    codeSwitchWords: ["eventual consistency", "use case", "strong consistency", "hot path", "analytics path", "scalable"],
    keyTerms: ["eventual consistency", "strong consistency", "architecture"],
    language: "mixed",
  },
  {
    id: "ts7",
    speaker: "S1",
    speakerLabel: "Interviewer",
    startTime: 172,
    endTime: 192,
    text: "Sangat komprehensif. Sekarang, kalau kita bicara soal pengalaman leadership — apakah Anda pernah mentoring junior engineers?",
    confidence: 0.96,
    isFinal: true,
    hasCodeSwitch: true,
    codeSwitchWords: ["leadership", "mentoring", "junior engineers"],
    keyTerms: ["leadership", "mentoring"],
    language: "mixed",
  },
  {
    id: "ts8",
    speaker: "S2",
    speakerLabel: "Candidate",
    startTime: 194,
    endTime: 230,
    text: "Ya, saya pernah menjadi tech lead untuk tim kecil berisi 4 orang engineer. Saya biasanya melakukan pair programming dan code review rutin setiap minggu. Menurut saya, yang paling penting adalah membangun psychological safety dalam tim — semua orang harus merasa nyaman untuk bertanya dan membuat kesalahan.",
    confidence: 0.92,
    isFinal: true,
    hasCodeSwitch: true,
    codeSwitchWords: ["tech lead", "pair programming", "code review", "psychological safety"],
    keyTerms: ["tech lead", "pair programming", "code review", "psychological safety"],
    language: "mixed",
  },
  {
    id: "ts9",
    speaker: "S1",
    speakerLabel: "Interviewer",
    startTime: 232,
    endTime: 250,
    text: "Bagus sekali. Mari kita lanjut ke technical deep dive. Bisa Anda jelaskan bagaimana Anda akan mendesain sistem antrian untuk payment gateway?",
    confidence: 0.95,
    isFinal: true,
    hasCodeSwitch: true,
    codeSwitchWords: ["technical deep dive", "payment gateway"],
    keyTerms: ["payment gateway", "queue design"],
    language: "mixed",
  },
  {
    id: "ts10",
    speaker: "S2",
    speakerLabel: "Candidate",
    startTime: 252,
    endTime: 320,
    text: "Untuk payment gateway, saya akan mempertimbangkan beberapa hal. Pertama, kita butuh idempotency key untuk setiap transaksi agar tidak ada double charging. Kedua, retry logic dengan exponential backoff. Ketiga, dead letter queue untuk transaksi yang gagal berulang kali. Dan keempat, observability — setiap transaksi harus punya trace ID yang bisa kita follow dari ujung ke ujung.",
    confidence: 0.89,
    isFinal: true,
    hasCodeSwitch: true,
    codeSwitchWords: ["idempotency key", "double charging", "retry logic", "exponential backoff", "dead letter queue", "observability", "trace ID"],
    keyTerms: ["idempotency", "retry logic", "dead letter queue", "observability"],
    language: "mixed",
  },
  {
    id: "ts11",
    speaker: "S1",
    speakerLabel: "Interviewer",
    startTime: 322,
    endTime: 340,
    text: "Jawaban yang sangat structured. Saya terkesan dengan pendekatan sistematis Anda. Ada pertanyaan dari Anda untuk kami?",
    confidence: 0.97,
    isFinal: true,
    hasCodeSwitch: true,
    codeSwitchWords: ["structured"],
    keyTerms: [],
    language: "mixed",
  },
  {
    id: "ts12",
    speaker: "S2",
    speakerLabel: "Candidate",
    startTime: 342,
    endTime: 390,
    text: "Tentu. Saya ingin tahu lebih lanjut tentang tech stack yang digunakan di PT Mandiri Teknologi, khususnya untuk core banking system yang baru. Apakah ada rencana untuk migrate ke cloud-native architecture dalam waktu dekat?",
    confidence: 0.93,
    isFinal: true,
    hasCodeSwitch: true,
    codeSwitchWords: ["tech stack", "core banking system", "cloud-native architecture"],
    keyTerms: ["tech stack", "cloud-native", "migration"],
    language: "mixed",
  },
];

export const TRANSCRIPT_I2: TranscriptSegment[] = [
  {
    id: "ts2_1",
    speaker: "S1",
    speakerLabel: "Interviewer",
    startTime: 5,
    endTime: 22,
    text: "Halo Rizky, senang bertemu dengan Anda. Kita langsung mulai ya. Bisa ceritakan tentang product yang paling Anda banggakan di OVO?",
    confidence: 0.96,
    isFinal: true,
    hasCodeSwitch: true,
    codeSwitchWords: ["product"],
    language: "mixed",
  },
  {
    id: "ts2_2",
    speaker: "S2",
    speakerLabel: "Candidate",
    startTime: 24,
    endTime: 65,
    text: "Terima kasih Bu Sari. Produk yang paling saya banggakan adalah fitur OVO PayLater yang kami launch tahun lalu. Dari ideasi sampai launch hanya butuh empat bulan, dengan tim cross-functional yang terdiri dari engineering, design, dan risk. Kami berhasil onboard 200 ribu pengguna di bulan pertama.",
    confidence: 0.94,
    isFinal: true,
    hasCodeSwitch: true,
    codeSwitchWords: ["launch", "cross-functional", "engineering", "design", "risk", "onboard"],
    keyTerms: ["OVO PayLater", "cross-functional", "onboard"],
    language: "mixed",
  },
  {
    id: "ts2_3",
    speaker: "S1",
    speakerLabel: "Interviewer",
    startTime: 67,
    endTime: 85,
    text: "Mengesankan. Bagaimana Anda menentukan prioritas fitur, terutama ketika ada pressure dari berbagai stakeholder?",
    confidence: 0.95,
    isFinal: true,
    hasCodeSwitch: true,
    codeSwitchWords: ["pressure", "stakeholder"],
    keyTerms: ["prioritization", "stakeholder"],
    language: "mixed",
  },
  {
    id: "ts2_4",
    speaker: "S2",
    speakerLabel: "Candidate",
    startTime: 87,
    endTime: 140,
    text: "Saya menggunakan kombinasi framework ICE scoring dan RICE untuk prioritisasi awal, tapi yang lebih penting adalah memastikan alignment dengan company OKR. Saya juga selalu melibatkan data — kita punya dashboard real-time untuk melihat user behavior, dan keputusan besar harus didukung dengan A/B test yang signifikan secara statistik.",
    confidence: 0.91,
    isFinal: true,
    hasCodeSwitch: true,
    codeSwitchWords: ["framework", "ICE scoring", "RICE", "alignment", "OKR", "dashboard", "real-time", "user behavior", "A/B test"],
    keyTerms: ["ICE scoring", "RICE", "OKR", "A/B test"],
    language: "mixed",
  },
];

export const TRANSCRIPT_I3: TranscriptSegment[] = [
  {
    id: "ts3_1",
    speaker: "S1",
    speakerLabel: "Interviewer",
    startTime: 3,
    endTime: 25,
    text: "Selamat pagi Pak Hendra. Terima kasih sudah menyempatkan waktu. Posisi ini sangat strategis bagi BRN karena kami sedang dalam proses transformasi digital yang harus tetap comply dengan ketentuan OJK.",
    confidence: 0.97,
    isFinal: true,
    hasCodeSwitch: false,
    keyTerms: ["OJK", "transformasi digital"],
    language: "id",
  },
  {
    id: "ts3_2",
    speaker: "S2",
    speakerLabel: "Candidate",
    startTime: 27,
    endTime: 65,
    text: "Selamat pagi Pak Ahmad. Saya memahami situasi tersebut dengan baik. Di Bank Mandiri, saya juga mengalami hal serupa ketika kami mengimplementasikan sistem penilaian kredit digital yang harus memenuhi POJK Nomor 40 tahun 2019 tentang penilaian kualitas aset bank umum.",
    confidence: 0.95,
    isFinal: true,
    hasCodeSwitch: false,
    keyTerms: ["POJK", "penilaian kredit", "Bank Mandiri"],
    language: "id",
  },
  {
    id: "ts3_3",
    speaker: "S1",
    speakerLabel: "Interviewer",
    startTime: 67,
    endTime: 90,
    text: "Bagus. Coba Anda jelaskan bagaimana pendekatan Anda dalam mengelola risiko konsentrasi kredit, terutama untuk debitur besar?",
    confidence: 0.96,
    isFinal: true,
    hasCodeSwitch: false,
    keyTerms: ["risiko konsentrasi kredit", "debitur"],
    language: "id",
  },
  {
    id: "ts3_4",
    speaker: "S2",
    speakerLabel: "Candidate",
    startTime: 92,
    endTime: 155,
    text: "Untuk risiko konsentrasi, saya selalu menggunakan pendekatan berlapis. Pertama, kami menetapkan BMPK internal yang lebih konservatif dari ketentuan OJK — biasanya kami batasi di 15% dari modal tier 1. Kedua, kami melakukan stress testing triwulanan dengan skenario makro yang buruk. Ketiga, kami membangun sistem early warning yang bisa mendeteksi tanda-tanda deteriorasi kualitas kredit sejak dini.",
    confidence: 0.93,
    isFinal: true,
    hasCodeSwitch: false,
    keyTerms: ["BMPK", "modal tier 1", "stress testing", "early warning"],
    language: "id",
  },
];

// ─── Interview Reviews (Post-Interview AI) ────────────────────────────────────

export const REVIEW_I1: InterviewReview = {
  interviewId: "i1",
  summaryId: "sum-i1",
  overallId: "ovr-i1",
  summaryBahasa:
    "Arief Rahmat Hidayat menunjukkan kompetensi teknis yang sangat kuat dalam area distributed systems, terutama berdasarkan pengalamannya di Tokopedia membangun sistem pemrosesan order dengan throughput tinggi. Kandidat memiliki pemahaman mendalam tentang konsistensi data, strategi sharding PostgreSQL, dan arsitektur Kafka. Kemampuan leadership-nya terbukti dari pengalamannya sebagai tech lead dan pendekatan mentoring yang berpusat pada psychological safety. Secara keseluruhan, kandidat sangat sesuai dengan kebutuhan posisi Senior Software Engineer Backend di PT Mandiri Teknologi.",
  summaryEnglish:
    "Arief Rahmat Hidayat demonstrated outstanding technical competency in distributed systems, drawing from his experience at Tokopedia building high-throughput order processing systems. The candidate possesses deep knowledge of data consistency models, PostgreSQL sharding strategies, and Kafka-based messaging architectures. His leadership capability was evident through his tech lead experience and a mentoring philosophy centered on psychological safety. Overall, the candidate is an excellent fit for the Senior Backend Engineer role at PT Mandiri Teknologi.",
  actionItems: [
    {
      id: "ai1",
      text: "Lakukan reference check dengan ex-manager di Tokopedia",
      assignee: "Sari Dewi Kusuma",
      dueDate: "2026-06-20",
      priority: "high",
      done: false,
    },
    {
      id: "ai2",
      text: "Kirimkan technical assessment untuk validasi Go skills",
      assignee: "Budi Hartono",
      dueDate: "2026-06-18",
      priority: "high",
      done: true,
    },
    {
      id: "ai3",
      text: "Persiapkan offer letter jika reference check oke",
      assignee: "Sari Dewi Kusuma",
      dueDate: "2026-06-25",
      priority: "medium",
      done: false,
    },
    {
      id: "ai4",
      text: "Koordinasi dengan tim IT untuk onboarding setup",
      assignee: "Budi Hartono",
      dueDate: "2026-07-01",
      priority: "low",
      done: false,
    },
  ],
  topicSegments: [
    {
      id: "top1",
      topic: "Introduction & Background",
      startTime: 0,
      endTime: 50,
      summaryLine: "Pembukaan dan pengenalan latar belakang kandidat di Tokopedia.",
      keywords: ["Tokopedia", "background", "platform engineering"],
    },
    {
      id: "top2",
      topic: "Distributed Systems Deep Dive",
      startTime: 50,
      endTime: 175,
      summaryLine: "Diskusi mendalam tentang eventual consistency, sharding, dan arsitektur dua layer.",
      keywords: ["eventual consistency", "sharding", "Go", "Kafka", "PostgreSQL"],
    },
    {
      id: "top3",
      topic: "Leadership & Mentoring",
      startTime: 175,
      endTime: 235,
      summaryLine: "Pengalaman tech lead dan filosofi mentoring kandidat.",
      keywords: ["tech lead", "mentoring", "psychological safety", "pair programming"],
    },
    {
      id: "top4",
      topic: "System Design: Payment Queue",
      startTime: 235,
      endTime: 325,
      summaryLine: "Kandidat mendesain sistem antrian payment gateway dengan idempotency dan observability.",
      keywords: ["payment gateway", "idempotency", "dead letter queue", "trace ID"],
    },
    {
      id: "top5",
      topic: "Q&A & Closing",
      startTime: 325,
      endTime: 390,
      summaryLine: "Kandidat mengajukan pertanyaan strategis tentang cloud-native migration.",
      keywords: ["cloud-native", "migration", "tech stack"],
    },
  ],
  keyDecisions: [
    {
      id: "kd1",
      decision: "Lanjutkan ke tahap offer",
      madeBy: "Budi Hartono",
      timestamp: 385,
      context: "Berdasarkan performa teknis dan fit budaya yang sangat baik",
    },
    {
      id: "kd2",
      decision: "Tetapkan level Senior II (bukan Principal)",
      madeBy: "Budi Hartono",
      timestamp: 370,
      context: "Experience sangat kuat tapi belum ada track record memimpin tim lebih dari 5 orang",
    },
  ],
  overallRecommendation: "strong_hire",
  strengthHighlights: [
    "Pengalaman distributed systems di skala production yang nyata (50k TPS)",
    "Pemahaman mendalam tentang consistency trade-offs",
    "Leadership mindset yang matang dengan fokus pada psychological safety",
    "Kemampuan system design yang terstruktur dan komprehensif",
  ],
  concernAreas: [
    "Tim terkecil yang pernah dipimpin hanya 4 orang — perlu validasi skalabilitas leadership",
    "Belum ada pengalaman langsung di industri fintech yang diregulasi",
  ],
  generatedAt: "2026-06-10T12:15:00",
};

export const REVIEW_I2: InterviewReview = {
  interviewId: "i2",
  summaryId: "sum-i2",
  overallId: "ovr-i2",
  summaryBahasa:
    "Rizky Pratama Nugroho memperlihatkan keahlian product management yang matang dengan portofolio nyata dari OVO. Kandidat mampu mengelola produk dari ideasi hingga launch dalam waktu singkat dengan hasil yang signifikan. Pendekatan data-driven dan penggunaan framework prioritisasi yang tepat menunjukkan kematangan sebagai PM senior. Kandidat memiliki pemahaman ekosistem pembayaran Indonesia yang komprehensif.",
  summaryEnglish:
    "Rizky Pratama Nugroho demonstrated mature product management skills with real portfolio evidence from OVO. The candidate is capable of managing products from ideation to launch within tight timelines with measurable results. His data-driven approach and use of appropriate prioritization frameworks (RICE, ICE) reflect PM seniority. The candidate has comprehensive understanding of Indonesia's payments ecosystem.",
  actionItems: [
    {
      id: "ai5",
      text: "Validasi angka 200k onboarding dengan referensi internal OVO",
      assignee: "Sari Dewi Kusuma",
      dueDate: "2026-06-18",
      priority: "high",
      done: false,
    },
    {
      id: "ai6",
      text: "Jadwalkan interview panel dengan CEO dan Head of Engineering",
      assignee: "Sari Dewi Kusuma",
      dueDate: "2026-06-20",
      priority: "high",
      done: false,
    },
  ],
  topicSegments: [
    {
      id: "top6",
      topic: "OVO PayLater Case Study",
      startTime: 5,
      endTime: 90,
      summaryLine: "Rizky menceritakan peluncuran OVO PayLater dan pencapaian 200k user di bulan pertama.",
      keywords: ["OVO PayLater", "launch", "cross-functional"],
    },
    {
      id: "top7",
      topic: "Prioritization Framework",
      startTime: 90,
      endTime: 145,
      summaryLine: "Penggunaan RICE, ICE scoring, dan alignment dengan OKR perusahaan.",
      keywords: ["RICE", "ICE", "OKR", "A/B test", "data-driven"],
    },
  ],
  keyDecisions: [
    {
      id: "kd3",
      decision: "Lanjutkan ke final round interview",
      madeBy: "Sari Dewi Kusuma",
      timestamp: 265,
      context: "Kandidat menunjukkan kecocokan yang sangat baik dengan visi produk perusahaan",
    },
  ],
  overallRecommendation: "hire",
  strengthHighlights: [
    "Track record nyata: 200k user onboarding di bulan pertama",
    "Framework berpikir yang terstruktur (RICE + OKR alignment)",
    "Pemahaman ekosistem pembayaran Indonesia yang dalam",
  ],
  concernAreas: [
    "Belum ada pengalaman mengelola PM lain (individual contributor track)",
    "Perlu asesmen lebih dalam tentang technical product sense",
  ],
  generatedAt: "2026-06-08T16:30:00",
};

// ─── Glossary ─────────────────────────────────────────────────────────────────

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  // Finance terms
  {
    id: "g1",
    tenantId: "t3",
    term: "BMPK",
    expansion: "Batas Maksimum Pemberian Kredit",
    category: "finance",
    hitCount: 47,
    lastSeen: "2026-06-12",
    addedBy: "Ahmad Fauzi",
    addedAt: "2024-01-10",
  },
  {
    id: "g2",
    tenantId: "t3",
    term: "POJK",
    expansion: "Peraturan Otoritas Jasa Keuangan",
    category: "finance",
    hitCount: 83,
    lastSeen: "2026-06-15",
    addedBy: "Ahmad Fauzi",
    addedAt: "2024-01-10",
  },
  {
    id: "g3",
    tenantId: "t3",
    term: "KPMM",
    expansion: "Kewajiban Penyediaan Modal Minimum",
    category: "banking",
    hitCount: 31,
    lastSeen: "2026-06-10",
    addedBy: "Ahmad Fauzi",
    addedAt: "2024-02-05",
  },
  {
    id: "g4",
    tenantId: "t1",
    term: "KYC",
    expansion: "Know Your Customer",
    category: "finance",
    hitCount: 124,
    lastSeen: "2026-06-17",
    addedBy: "Sari Dewi",
    addedAt: "2024-01-15",
  },
  {
    id: "g5",
    tenantId: "t1",
    term: "AML",
    expansion: "Anti-Money Laundering",
    category: "finance",
    hitCount: 89,
    lastSeen: "2026-06-16",
    addedBy: "Sari Dewi",
    addedAt: "2024-01-15",
  },
  // Tech terms
  {
    id: "g6",
    tenantId: "t2",
    term: "DLQ",
    expansion: "Dead Letter Queue",
    category: "tech",
    hitCount: 18,
    lastSeen: "2026-06-15",
    addedBy: "Rina Agustina",
    addedAt: "2024-03-12",
  },
  {
    id: "g7",
    tenantId: "t1",
    term: "RTO",
    expansion: "Recovery Time Objective",
    category: "tech",
    hitCount: 22,
    lastSeen: "2026-06-11",
    addedBy: "Budi Hartono",
    addedAt: "2024-02-20",
  },
  {
    id: "g8",
    tenantId: "t1",
    term: "SLA",
    expansion: "Service Level Agreement",
    category: "tech",
    hitCount: 156,
    lastSeen: "2026-06-17",
    addedBy: "Budi Hartono",
    addedAt: "2024-02-20",
  },
  // HR terms
  {
    id: "g9",
    tenantId: "t1",
    term: "OKR",
    expansion: "Objectives and Key Results",
    category: "hr",
    hitCount: 67,
    lastSeen: "2026-06-14",
    addedBy: "Sari Dewi",
    addedAt: "2024-01-20",
  },
  {
    id: "g10",
    tenantId: "t1",
    term: "PKB",
    expansion: "Perjanjian Kerja Bersama",
    category: "hr",
    hitCount: 12,
    lastSeen: "2026-06-05",
    addedBy: "Sari Dewi",
    addedAt: "2024-03-01",
  },
  // Custom acronyms
  {
    id: "g11",
    tenantId: "t1",
    term: "SDKM",
    expansion: "Sistem Data Karyawan Mandiri",
    category: "custom",
    hitCount: 5,
    lastSeen: "2026-06-10",
    addedBy: "Sari Dewi",
    addedAt: "2024-04-15",
  },
  {
    id: "g12",
    tenantId: "t3",
    term: "SPGC",
    expansion: "Sistem Penilaian Grade Kredit",
    category: "custom",
    hitCount: 9,
    lastSeen: "2026-06-12",
    addedBy: "Ahmad Fauzi",
    addedAt: "2024-05-20",
  },
];

// ─── NLP Settings ─────────────────────────────────────────────────────────────

export const NLP_SETTINGS: NLPSettings = {
  tenantId: "t1",
  enablePunctuation: true,
  enableInverseTextNorm: true,
  enableFillerRemoval: true,
  fillerWords: ["ee", "mm", "hmm", "anu", "gitu", "ya kan", "intinya"],
  enableCodeSwitchLabelling: true,
  codeSwitchHighlightColor: "yellow",
  enableParticleNorm: true,
  particlesTarget: ["lah", "kan", "nih", "dong", "deh", "sih"],
  enableGlossaryCorrection: true,
  confidenceThreshold: 0.75,
  asrLatencyTargetMs: 400,
  diarizationEnabled: true,
  minSpeakers: 2,
  maxSpeakers: 4,
};

// ─── Admin Stats ──────────────────────────────────────────────────────────────

export const ADMIN_STATS: AdminStats = {
  totalInterviews: 847,
  totalHoursTranscribed: 424,
  totalCostThisMonth: 8480000,
  activeTenantsCount: 3,
  avgWER: 8.8,
  avgDER: 5.7,
  interviewsThisWeek: 38,
  tenantBreakdown: [
    {
      tenantId: "t1",
      tenantName: "PT Mandiri Teknologi",
      interviewsThisMonth: 142,
      hoursTranscribed: 142,
      costThisMonth: 2840000,
      asrProvider: "Google STT",
      wer: 8.2,
      der: 5.1,
      planTier: "enterprise",
      complianceFlag: false,
    },
    {
      tenantId: "t2",
      tenantName: "StartupID",
      interviewsThisMonth: 68,
      hoursTranscribed: 68,
      costThisMonth: 1360000,
      asrProvider: "Whisper",
      wer: 11.4,
      der: 7.8,
      planTier: "growth",
      complianceFlag: false,
    },
    {
      tenantId: "t3",
      tenantName: "Bank Rakyat Nusantara",
      interviewsThisMonth: 214,
      hoursTranscribed: 214,
      costThisMonth: 4280000,
      asrProvider: "Azure Speech",
      wer: 6.7,
      der: 4.3,
      planTier: "enterprise",
      complianceFlag: true,
    },
  ],
};

// ─── Streaming transcript lines for live mock ──────────────────────────────

export const LIVE_TRANSCRIPT_LINES: TranscriptSegment[] = [
  {
    id: "live1",
    speaker: "S1",
    speakerLabel: "Interviewer",
    startTime: 5,
    endTime: 18,
    text: "Selamat pagi Fajar! Selamat datang di interview hari ini. Kita akan membahas beberapa topik teknis dan juga tentang pengalaman kamu.",
    confidence: 0.96,
    isFinal: true,
    hasCodeSwitch: false,
    language: "id",
  },
  {
    id: "live2",
    speaker: "S2",
    speakerLabel: "Candidate",
    startTime: 20,
    endTime: 32,
    text: "Selamat pagi Bu Rina! Senang sekali bisa ada di sini. Saya sudah sangat excited untuk bisa bergabung dengan tim StartupID.",
    confidence: 0.94,
    isFinal: true,
    hasCodeSwitch: true,
    codeSwitchWords: ["excited"],
    language: "mixed",
  },
  {
    id: "live3",
    speaker: "S1",
    speakerLabel: "Interviewer",
    startTime: 34,
    endTime: 52,
    text: "Bagus. Kita mulai dari portfolio kamu. Ceritakan satu project yang paling challenging yang pernah kamu kerjakan sebagai full-stack developer.",
    confidence: 0.95,
    isFinal: true,
    hasCodeSwitch: true,
    codeSwitchWords: ["portfolio", "project", "challenging", "full-stack developer"],
    language: "mixed",
  },
  {
    id: "live4",
    speaker: "S2",
    speakerLabel: "Candidate",
    startTime: 54,
    endTime: 90,
    text: "Project yang paling berkesan adalah ketika saya membangun sistem e-commerce untuk UMKM lokal. Saya pakai Next.js untuk frontend dan Node.js untuk backend-nya. Yang bikin challenging adalah integrasi payment gateway lokal yang dokumentasinya kurang lengkap.",
    confidence: 0.92,
    isFinal: true,
    hasCodeSwitch: true,
    codeSwitchWords: ["project", "e-commerce", "frontend", "backend", "challenging", "payment gateway"],
    keyTerms: ["Next.js", "Node.js", "payment gateway", "UMKM"],
    language: "mixed",
  },
  {
    id: "live5",
    speaker: "S1",
    speakerLabel: "Interviewer",
    startTime: 92,
    endTime: 110,
    text: "Interesting. Berapa lama kamu menyelesaikan project itu, dan bagaimana kamu mengelola timeline-nya sendirian?",
    confidence: 0.93,
    isFinal: true,
    hasCodeSwitch: true,
    codeSwitchWords: ["interesting", "project", "timeline"],
    language: "mixed",
  },
  {
    id: "live6",
    speaker: "S2",
    speakerLabel: "Candidate",
    startTime: 112,
    endTime: 148,
    text: "Kurang lebih tiga bulan untuk versi pertama. Saya menggunakan pendekatan agile secara personal — setiap minggu saya review sprint yang sudah saya set sendiri. Pakai Notion untuk tracking tasks dan GitHub Projects untuk board-nya.",
    confidence: 0.91,
    isFinal: true,
    hasCodeSwitch: true,
    codeSwitchWords: ["agile", "sprint", "review", "tracking", "tasks", "board"],
    keyTerms: ["agile", "Notion", "GitHub Projects"],
    language: "mixed",
  },
  {
    id: "live7",
    speaker: "S1",
    speakerLabel: "Interviewer",
    startTime: 150,
    endTime: 168,
    text: "Kamu menyebut Next.js — seberapa familiar kamu dengan App Router di Next.js 14? Sudah pakai di production?",
    confidence: 0.96,
    isFinal: true,
    hasCodeSwitch: true,
    codeSwitchWords: ["App Router", "production"],
    keyTerms: ["Next.js 14", "App Router"],
    language: "mixed",
  },
  {
    id: "live8",
    speaker: "S2",
    speakerLabel: "Candidate",
    startTime: 170,
    endTime: 210,
    text: "Ya, saya sudah pakai App Router sejak Next.js 13 keluar. Saya sangat appreciate dengan Server Components karena bisa reduce bundle size secara signifikan. Di project terakhir saya, kami berhasil menurunkan First Contentful Paint dari 3.2 detik ke 0.8 detik dengan kombinasi RSC dan streaming.",
    confidence: 0.89,
    isFinal: true,
    hasCodeSwitch: true,
    codeSwitchWords: ["App Router", "Server Components", "reduce", "bundle size", "First Contentful Paint", "streaming"],
    keyTerms: ["App Router", "Server Components", "RSC", "First Contentful Paint"],
    language: "mixed",
  },
  {
    id: "live9",
    speaker: "S1",
    speakerLabel: "Interviewer",
    startTime: 212,
    endTime: 232,
    text: "Sangat teknis dan konkret. Satu lagi — bagaimana pendekatan kamu terhadap testing? Unit test, integration test?",
    confidence: 0.95,
    isFinal: true,
    hasCodeSwitch: true,
    codeSwitchWords: ["testing", "unit test", "integration test"],
    keyTerms: ["testing", "unit test"],
    language: "mixed",
  },
  {
    id: "live10",
    speaker: "S2",
    speakerLabel: "Candidate",
    startTime: 234,
    endTime: 270,
    text: "Saya percaya pada pendekatan piramida testing. Unit test untuk logic yang isolated pakai Vitest atau Jest. Integration test untuk API routes. Dan untuk E2E saya pakai Playwright karena lebih reliable dari Cypress untuk SSR apps. Coverage target saya biasanya di atas 80 persen untuk critical paths.",
    confidence: 0.9,
    isFinal: true,
    hasCodeSwitch: true,
    codeSwitchWords: ["unit test", "logic", "isolated", "Integration test", "API routes", "E2E", "reliable", "SSR apps", "Coverage", "critical paths"],
    keyTerms: ["Vitest", "Jest", "Playwright", "E2E", "coverage"],
    language: "mixed",
  },
];

// Helper functions
export function getCandidatesByJobId(jobId: string): Candidate[] {
  return CANDIDATES.filter((c) => c.jobId === jobId);
}

export function getCandidatesByStage(
  jobId: string,
  stage: string
): Candidate[] {
  return CANDIDATES.filter((c) => c.jobId === jobId && c.stage === stage);
}

export function getJobById(id: string): Job | undefined {
  return JOBS.find((j) => j.id === id);
}

export function getCandidateById(id: string): Candidate | undefined {
  return CANDIDATES.find((c) => c.id === id);
}

export function getInterviewById(id: string): Interview | undefined {
  return INTERVIEWS.find((i) => i.id === id);
}

export function getTenantById(id: string): Tenant | undefined {
  return TENANTS.find((t) => t.id === id);
}

export function getTranscriptByInterviewId(
  id: string
): TranscriptSegment[] {
  if (id === "i1") return TRANSCRIPT_I1;
  if (id === "i2") return TRANSCRIPT_I2;
  if (id === "i3") return TRANSCRIPT_I3;
  return [];
}

export function getReviewByInterviewId(
  id: string
): InterviewReview | undefined {
  if (id === "i1") return REVIEW_I1;
  if (id === "i2") return REVIEW_I2;
  return undefined;
}

export function formatCurrency(amount: number, currency = "IDR"): string {
  if (currency === "IDR") {
    if (amount >= 1000000) {
      return `Rp ${(amount / 1000000).toFixed(1)}jt`;
    }
    return `Rp ${amount.toLocaleString("id-ID")}`;
  }
  return `${currency} ${amount.toLocaleString()}`;
}

export function formatDuration(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return `${m.toString().padStart(2, "0")}:${s.toString().padStart(2, "0")}`;
}

export function formatTimestamp(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = seconds % 60;
  if (h > 0) {
    return `${h}:${m.toString().padStart(2, "0")}:${s.toString().padStart(2, "0")}`;
  }
  return `${m.toString().padStart(2, "0")}:${s.toString().padStart(2, "0")}`;
}
